### ISSUE TITLE
Error with django 1.8.3

### ISSUE THREAD

**Issue by cheves505** [michiya/django-pyodbc-azure#103]
I just trying to run my project and i get this error

django.db.utils.ProgrammingError: ('42S02', "[42S02] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid object name 'django_migrations'. (208) (SQLExecDirectW)")

my config is 

DATABASES = { 
    'default': { 
        'NAME': 'intrack',   
        'ENGINE': 'sql_server.pyodbc', 
        'HOST': 'DESKTOP-4LF50CB',  
        'USER': 'sa', #usuario de autenticacion SQL 
        'PASSWORD': 'passwordofdb', 
        'OPTIONS':{ 
            'unicode_results':True, 
            'extra_params': 'ClientCharset=utf8', 
             'driver': 'SQL Server',
        } 
    } 
}

**Comment by meet-bhagdev** [comment]
@cheves505 did you create the database intrack?

**Comment by cheves505** [comment]
yes, the database is there 
![intrack_error](https://user-images.githubusercontent.com/13157631/28433286-488edac8-6d48-11e7-9480-f595fb69e4b8.PNG)

**Comment by cheves505** [comment]
Hello the error was because of the prefix intrack in the database and the way we migrate the data form mysql to SQL Server

**Comment by ghost** [comment]
@cheves505 have you run into this same error message when you try to `runserver` with a different, unused schema? please check out my issue here if you have: https://github.com/michiya/django-pyodbc-azure/issues/133
