### ISSUE TITLE
DjangoUnicodeDecodeError: 'utf8' codec can't decode byte

### ISSUE THREAD

**Issue by toscanelli** [michiya/django-pyodbc-azure#12]
I use pyodbc-azure 1.1.5 to connect my django project to a SQL Server db. My client is SQL Server Native Client 11.0

When I try to open the corresponging change_list I get this error:
'utf8' codec can't decode byte 0xd1 in position 4: invalid continuation byte. You passed in 'ESPA\xd1A' (<type 'str'>)

The annoying character is Ñ. I've checked the encoding of my db and I got that is Modern_Spanish_CI_AS which, I believe, is equivalent to 'latin-1' or 'cp1252' (not sure).

I have tried to modify the pyodb\base.py replacing wherever utf-8 appears to cp1252 or latin1 (following tips described in issue 24), but the error is still referring to utf8.

What else can I do? (other than change the backend)

**Comment by shaib** [comment]
You don't quite give enough context -- e.g., where do you get the error from? django-pyodbc-azure? pyodbc itself? The Django field? Your own app?

It is strongly recommended, if you can, to use utf-8 in your database; if you can't, try looking for conversions to unicode -- you won't necessarily see "utf-8" mentioned, because it is the default.

Note:

``` !python
>>> unicode('ESPA\xd1A', 'utf-8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd1 in position 4: invalid continuation byte

>>> unicode('ESPA\xd1A')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 4: ordinal not in range(128)

>>> unicode('ESPA\xd1A', 'latin-1')
u'ESPA\xd1A'
```

**Comment by toscanelli** [comment]
Thank you, shaib.
I finally solve the problem finding this line in base.py

<pre> unicode_results = options.get('unicode_results', False) </pre>

So, it is necessary to set True the option 'unicode_results' in Django settings.
