### ISSUE TITLE
Django 2.0 Support

### ISSUE THREAD

**Issue by fredley** [michiya/django-pyodbc-azure#124]
Django 2.0 is not supported. Removing the version warning and trying to define pyodbc connections results in:

```
django.core.exceptions.ImproperlyConfigured: 'sql_server.pyodbc' isn't an available database backend.
Try using 'django.db.backends.XXX', where XXX is one of:
    'mysql', 'oracle', 'postgresql', 'sqlite3'
```

The Database backend API has changed considerably in Django 2.0:

https://docs.djangoproject.com/en/2.0/releases/2.0/#database-backend-api

**Comment by pekof** [comment]
Is there any progress on this question?
I'm considering forking this project, but if anyone made some work to support Django 2.0 I could join forces :)

p.s.  I made inquire on stackoverflow https://stackoverflow.com/questions/48112639/using-sql-server-with-django-2-0

**Comment by FlipperPA** [comment]
Hey, I've started work on 2.0 compatibility here: https://github.com/FlipperPA/django-pyodbc-azure/commits/azure-2.0

I've done a little bit of work on DB engines in the past, and figure I can give Michaya a head start. Not planning on a fork at all, just to contribute, but if others want to pitch it, it'd be appreciated!

**Comment by FlipperPA** [comment]
I've made some progress and started a Work In Progress P.R. here: https://github.com/michiya/django-pyodbc-azure/pull/129

Long story short: it now works with runserver and initial migrations and a fresh Django default Django project.

**Comment by michiya** [comment]
@FlipperPA Thanks for your contribution and sorry for my delay. I have pushed the new back-end codes which passed most of the tests in Django 2.0 to the new branch `azure-2.0` in this repo today, and I will publish it as a new version of the package on PyPI soon. Feel free to send me a new pull request if you find there is something more to be merged to the repo for better Django 2.0 compatibility.

**Comment by FlipperPA** [comment]
I've got a few minor clean up tweaks I think could help - I'll refresh to your upstream changes. I think a manual merge of the tweaks would be better that trying to do a merge conflict resolution for my sanity.

Do you think switching the default from FreeTDS to the MS driver on Linux is the right way to go? If so, I'll update the README to make sure this change is reflected. I know it would've tripped me up if I hadn't looked at the diff. Thanks again, @michiya!

**Comment by hetsch** [comment]
Thank's for working on django2 support @michiya and @FlipperPA. I get this error using the `azure-2` branch and `manage.py runserver`:

```
File "manage.py", line 21, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/flush.py", line 49, in handle
    allow_cascade=allow_cascade)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/sql.py", line 16, in sql_flush
    seqs = connection.introspection.sequence_list() if reset_sequences else ()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/introspection.py", line 127, in sequence_list
    sequence_list.extend(self.get_sequences(cursor, model._meta.db_table, model._meta.local_fields))
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/introspection.py", line 142, in get_sequences
    raise NotImplementedError('subclasses of BaseDatabaseIntrospection may require a get_sequences() method')
NotImplementedError: subclasses of BaseDatabaseIntrospection may require a get_sequences() method
```

**Comment by michiya** [comment]
django-pyodbc-azure for Django 2.0 is now available on PyPI. Try it out and let me know if you have any further questions.

**Comment by Delios82** [comment]
Hi, 

I installed according to the guide, but it gives me the following error, can you tell me a suggestion?

django.core.exceptions.ImproperlyConfigured: 'django-pyodbc-azure' isn't an available database backend.
Try using 'django.db.backends.XXX', where XXX is one of:
    'mysql', 'oracle', 'postgresql', 'sqlite3'

My Django version is 2.1.3

this is configuration from setting.py:

'default': {
        'ENGINE': 'sql_server.pyodbc', 
        'HOST': "XXXXX",
        'PORT': '1433',
        'NAME': "XXXX",
        'USER': "XXXXX",
        'PASSWORD': "XXXXX",
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'unicode_results': True,
        },
    },
}

**Comment by odhiambod** [comment]
My Installations are as follows:
$ pip freeze
Django==2.1.7
django-pyodbc==1.1.3
django-pyodbc-azure==2.1.0.0
pymssql==2.1.4
pyodbc==4.0.26
pytz==2018.9

**Comment by odhiambod** [comment]
And My working settings is 
DATABASES = {
    'default': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'mydb',
        'USER': 'sa',
        'PASSWORD': 'mypassword',
        'HOST': '192.168.2.61',
        'PORT': '',

        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
}
