### ISSUE TITLE
Project unmaintained?

### ISSUE THREAD

**Issue by shadiakiki1986** [michiya/django-pyodbc-azure#125]
Hello @michiya 
Is this project unmaintained anymore?

**Comment by shadiakiki1986** [comment]
Dear All
This project was great, but it seems that the issues are piling up, PR's are being filed but not merged, and the forks are multiplying. How are we going to combine our efforts to get this project up again?

Recent forkers
@optelgroup @movacek @isosphere @loftylabs @tax @OskarPersson @guifran001 @ivanchenkodmitry @jjmontalbo @WuXianglong @justinsg @nattster @mrbean-bremen @Awingu @tbock @chris-ninz @ozgurisil @bsnux @nschonni @FlipperPA @kippr @dlo @kdazzle

Recent issue reporters
@fredley @bcahlit @isosphere @twschiller @jingwei218 @TheHamz @guifran001 @sanjtech @wzrd-clss @tylerwmmars @FlipperPA @stuartaccent @2ps 

Recent PRers
@isosphere @OskarPersson @guifran001 @justing @nattster @bsnux @nschonni @shlee322 @tax

**Comment by michiya** [comment]
Sorry for my long delay in updating the package. I have been too busy to keep this project up-to-date for months, but I should be able to get back to it soon. I hope I can publish a new version of the package which supports Django 2.0 in this month.

**Comment by dlo** [comment]
@shadiakiki1986 I forked the original django-pyodbc over 4 years ago. Not sure if I would call that a recent fork. :)

**Comment by shadiakiki1986** [comment]
@michiya That's great news! Let me know if I can help with anything :+1: 

@dlo sorry about that. I was just copy-pasting the first pages of contributors to gather some feedback. I didn't know what else to do. I even filed a [stackoverflow question](https://stackoverflow.com/questions/47766691/for-a-github-repository-that-is-no-longer-maintained-how-do-developers-agree-on) asking what people do in these cases :smile:

**Comment by FlipperPA** [comment]
Thanks @michaya! If there's any contributions I can help with, let me know.

**Comment by FlipperPA** [comment]
Hey, I've started work on 2.0 compatibility here: https://github.com/FlipperPA/django-pyodbc-azure/commits/azure-2.0

I've done a little bit of work on DB engines in the past, and figure I can give Michaya a head start. Not planning on a fork at all, just to contribute, but if others want to pitch it, it'd be appreciated!

**Comment by FlipperPA** [comment]
I've made some progress and started a Work In Progress P.R. here: https://github.com/michiya/django-pyodbc-azure/pull/129

Long story short: it now works with runserver and initial migrations and a fresh Django default Django project.

**Comment by michiya** [comment]
django-pyodbc-azure for Django 2.0 is now available on PyPI. Try it out and let me know if you have any problem with it.

**Comment by shadiakiki1986** [comment]
Perfect. Thanks Michiya! :)

**Comment by TheHamz** [comment]
Tyvm!
