### ISSUE TITLE
Setting A Query Timeout 

### ISSUE THREAD

**Issue by lorddarkflare** [michiya/django-pyodbc-azure#126]
Based on this post by the author: https://github.com/lionheart/django-pyodbc/issues/18 the connection timeout can be set after the connection is established and this can act as a 'Query Timeout'. 

I have tested this myself with the following snippet:

```python
import pyodbc
import time

start = time.time()
try:
    conn = pyodbc.connect(
        "DRIVER=/usr/lib64/libtdsodbc.so.0;"
        "SERVER=10.10.10.10;"
        "PORT=1433;"
        "DATABASE=DEV_SERVER;"
        "UID=user;"
        "PWD=password;"
        "TDS_Version=7.3;", timeout=1)
    conn.timeout = 1
    cursor = conn.cursor()
    cursor.execute("WAITFOR DELAY '00:00:05'")
except:
    raise
finally:
    stop = time.time()
    print(stop - start)
```

Knowing this, is there a reason something like this was not implemented in this library? 

I am thinking of working on a PR for a 'query_timeout'. My testing has not showed any issue with this so far.

**Comment by michiya** [comment]
Thank you for the feedback. The feature is included in the latest release and now you can specify query timeout value by using query_timeout option in your database settings (ba68198).
