### ISSUE TITLE
Can't migrate from PositiveIntegerField to PositiveSmallIntegerField

### ISSUE THREAD

**Issue by twschiller** [michiya/django-pyodbc-azure#127]
Migration from `PositiveIntegerField` to `PositiveSmallIntegerField` fails on MSSQL because MSSQL refuses to change the column type from `int` to `smallint` due to the positive value constraint.

A workaround is to migrate from 'PositiveIntegerField' to 'IntegerField' to 'PositiveSmallIntegerField'. This drops the constraint before the migration

The migration succeeds on SQLLite and PostgreSQL. I haven't checked to see if the SQL is different for those, or if the DB behavior is different

**Comment by michiya** [comment]
Thank you for reporting. The fix for the issue is available on PyPI now. Let me know if you still see the same error after upgrading django-pyodbc-azure to the latest version.
