### ISSUE TITLE
Support for schema migration in upcoming Django 1.7

### ISSUE THREAD

**Issue by shlomiassaf** [michiya/django-pyodbc-azure#13]
Hi,

Are you guys planning to support the native migration API implemented in Django 1.7?

Since "South" is not longer maintained and now fully ported into native Django it means no MS-SQL support.

The new API expects the db backend to provide a set of schema change functions...
https://groups.google.com/d/msg/south-users/AvtbWkIbQjk/DjOyb3eYll8J

Thanks,

**Comment by michiya** [comment]
Thank you for the reminder. The new version of the backend that supports Django 1.7 is now available  on PyPI. Try it out and let me know if you find a bug.
