### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by beruic** [michiya/django-pyodbc-azure#130]
django-pyodbc-azure support Python 3?

**Comment by FlipperPA** [comment]
I've been running it on Python 3 for years without problems. What's the issue you're having?

**Comment by justinrsmith** [comment]
Yes Python 3 works just fine. Have ran it in production for two years now.

**Comment by beruic** [comment]
I just wanted to know beforehand, since it is not documented which python versions are supported.

**Comment by michiya** [comment]
This package complies with Django spec in terms of Python vesions to support. For example, django-pyodbc-azure 2.0.x.x supports Python 3.4/3.5/3.6 in accordance with Django 2.0 spec.
https://docs.djangoproject.com/en/2.0/faq/install/#what-python-version-can-i-use-with-django

You can also see them in the Categories section at the bottom of its PyPI page.
https://pypi.python.org/pypi/django-pyodbc-azure
