### ISSUE TITLE
GET Error while call store procedure in python with SQL-server

### ISSUE THREAD

**Issue by manali0** [michiya/django-pyodbc-azure#134]
`

down votefavorite | try: sql = "SET NOCOUNT ON;"\             "DECLARE @out int;"\             "DECLARE @timess time;"\             "EXEC [dbo].[VSM_isTradingHour] @date = ?,@isTrading = @out OUTPUT,@timestamp = @timess OUTPUT;"\             "SELECT @out,@timess As the_output;" cnxn = pypyodbc.connect("Trusted_Connection=yes;"                       "Driver={SQL Server};"                       "Server=SS-88-PC;"                       "Database=VirtualShareMarket;"                       "UID=sa;PWD=icreate") cursor = cnxn.cursor() params = ('2018-05-05',) cursor.execute(sql,params) rows= cursor.fetchall() print(rows)
-- | --

`

Error:---- %s ('24000', '[24000] [Microsoft][ODBC SQL Server Driver]Invalid cursor state')

**Comment by manali0** [comment]
Can any one tell me what is missing here?

**Comment by michiya** [comment]
I understand that you're trying to execute some T-SQL statements on your SQL Server using raw pypyodbc APIs. Unfortunately pypyodbc is not related to this project and I don't have an insight into it. I hope you will have helpful suggestions for your problem from pypyodbc developers.
https://github.com/jiangwen365/pypyodbc
