### ISSUE TITLE
Invalid Object Name

### ISSUE THREAD

**Issue by ghost** [michiya/django-pyodbc-azure#151]
When I add a new model in Django and attempt to run `python manage.py makemigrations` SQLServer throws an "Invalid object name: module_modelname" error. If I create the table in the database and run makemigrations, it completes but I can't migrate because the object already exists. If I delete the table in the database and run migrate, I get the same invalid object name error. 

SQL Server 12
Django/django-pyodbc-azuree 2.03

**Comment by Grinch101** [comment]
same here!
