### ISSUE TITLE
'sql_server.pyodbc' isn't an available database backend

### ISSUE THREAD

**Issue by encore133** [michiya/django-pyodbc-azure#152]
Tried to use SQL Server as the backend for Django, but I got this when debugging the web project. is there any setting missing here?

`  File "C:\Users\lenovo\PycharmProjects\untitled_django0316\venv\lib\site-packages\django\db\utils.py", line 125, in load_backend
    ) from e_user
django.core.exceptions.ImproperlyConfigured: 'sql_server.pyodbc' isn't an available database backend.
Try using 'django.db.backends.XXX', where XXX is one of:
    'mysql', 'oracle', 'postgresql', 'sqlite3'
`

Here's the database setting:
`
DATABASES = {                                         
    'default': {                                             
        'ENGINE': 'sql_server.pyodbc',                       
        'NAME': 'django_test',                               
        'USER': 'django_test',                               
        'PASSWORD': 'xxxxxx',                                
        'HOST': 'xx.xx.xx.xx',                              
        'PORT': ''                                           
        }                                                    
    }
`

Here's the python(3.6.3) environment:
Django (2.0.3)
django-pyodbc-azure (2.0.3.0)
pyodbc (4.0.22)

**Comment by FlipperPA** [comment]
What happens if you try to import it directly into the virtual environment?

```
(your_venv)$ python manage.py shell
>>> from sql_server import pyodbc
```

Does it import correctly?

**Comment by skewty** [comment]
I am having this issue but my situation is likely different.  I am trying to use Django ORM without a web app as follows:

```python
from somewhere.config import parse_config
from django import setup as django_setup
from django.conf import settings as django_settings

config = parse_config()
django_settings.configure(
    DEBUG=True,
    DATABASES={
        'default': {
            'ENGINE': 'sql_server.pyodbc',  # requires: pip install django-pyodbc-azure
            'NAME': config.database_name,
            'HOST': config.database_server,
            'USER': config.database_username,
            'PASSWORD': config.database_password,
            'OPTIONS': {
                'driver': 'ODBC Driver 11 for SQL Server',
            },
        },
    })
django_setup()


from django.db import models

class Room(models.Model):
    id = models.AutoField(primary_key=True, db_column='RoomID')
    name = models.CharField(max_length=25, db_column='RoomName')
    override_name = models.CharField(max_length=25, db_column='OverrideRoomName')

    class Meta:
        db_table = "DCS1Room"
        app_label = 'foo'

if __name__ == '__main__':
    Room.objects.get()
```

#### Any idea how I tell Django about this Engine so I don't get the following error?
```
'sql_server.pyodbc' isn't an available database backend.
Try using 'django.db.backends.XXX', where XXX is one of:
    'mysql', 'oracle', 'postgresql', 'sqlite3'
```

**Comment by odhiambod** [comment]
Please find my code that is working well
DATABASES = {
    'default': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'mydb',
        'USER': 'sa',
        'PASSWORD': 'Password#',
        'HOST': '192.168.2.61',
        'PORT': '',

        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
}

**Comment by saribala** [comment]
hi odhiambod i wrote  exactly like you but still i am facing that error

regards,
usharani saribala

**Comment by odhiambod** [comment]
what version of mssql are u running, because it will not work with mssql 2019

**Comment by saribala** [comment]
I am using sqlserver 2012

**Comment by saribala** [comment]
Thank you for your response. I have changed drive like this 'SQL Server Native Client 11.0' and install django-pyodbc-azure==1.8.3.0 now its working fine

regards,
Usharani saribala
