### ISSUE TITLE
FreeTDS datetime/datetime2 support

### ISSUE THREAD

**Issue by balazs-endresz** [michiya/django-pyodbc-azure#153]
Hi

My problem in a nutshell is that I had to remove these lines to get things working:
https://github.com/michiya/django-pyodbc-azure/blob/2.0.3.0/sql_server/pyodbc/base.py#L362

I checked and in fact `datetime2` doesn't get converted to python, however `datetime` does.

I'm using FreeTDS (`tds version = 8.0`) with SQL Server 2014 on Azure:

```
Microsoft SQL Azure (RTM) - 12.0.2000.8 
	Jan 30 2018 18:34:32 
	Copyright (C) 2017 Microsoft Corporation
```

So, even though `datetime2` is not properly supported that doesn't seem to be a problem for me, since we use only `datetime`.

Would it be possible to _not_ raise an exception upfront for the lack of `datetime2` support? Would maybe just a warning suffice?

Thanks
Balazs

**Comment by michiya** [comment]
Unfortunately not. django-pyodbc-azure doesn't support the old `datetime` type anymore following the Django 2 implementation policy. See #109 for more details.

The value 8.0 is invalid for `tds version`. It should work without causing an error by setting `tds version` to 7.3 as described in #142 if you have FreeTDS 0.95 or newer.

You can also use Django and django-pyodbc-azure 1.11 which still support the old `datetime` type if you need to stick to FreeTDS older than 0.95.

**Comment by balazs-endresz** [comment]
Ah, apologies, I was looking at freetds.conf (it says 8.0 there for some reason) but apparently it is 4.2 and even freetds itself is only 0.91, so we'll definitely need to upgrade that first:

```
$ tsql -C
Compile-time settings (established with the "configure" script)
                            Version: freetds v0.91
             freetds.conf directory: /etc/freetds
     MS db-lib source compatibility: no
        Sybase binary compatibility: yes
                      Thread safety: yes
                      iconv library: yes
                        TDS version: 4.2
                              iODBC: no
                           unixodbc: yes
              SSPI "trusted" logins: no
                           Kerberos: no
```

Thank you for the quick response and the pointers though!
