### ISSUE TITLE
`supports_mars` attribute error when using multiple databases. 

### ISSUE THREAD

**Issue by ScottBarkman** [michiya/django-pyodbc-azure#158]
Ran into an issue when I was attempting to use this with multiple databases (MS sql server & postgresql) Whenever I would run a query on the sql server, followed by one on postgres - the postgresql one would fail with `DatabaseWrapper has no attribute supports_mars`

I traced this back to a method (`_cursor_iter`) inside of `pyodbc/compile.py` which appeared to be running on each database connection, including the postgresql one. 

Adding a simple @ line 84: 
````
if not hasattr(cursor.db, "supports_mars"):
    cursor.db.supports_mars = False;
````
solves the issue.

**Comment by jmelloy** [comment]
I've been having this exact issue.

**Comment by michiya** [comment]
Thank you for reporting and sorry for inconvenience. I have made the fix for this and pushed it to PyPI. Let me know if you still see the same error after upgrading django-pyodbc-azure to the latest version.

**Comment by ScottBarkman** [comment]
No worries, thanks for the fix. I wasn't that confident with always assuming it doesn't support mars or I would have submitted a pull request. 

Thanks again - works great installed from pypi
