### ISSUE TITLE
Trouble running tests with Django 1.7

### ISSUE THREAD

**Issue by olivergeorge** [michiya/django-pyodbc-azure#16]
Hello

When I run tests on one of my apps it reports "Programming error: attempt to use closed cursor".  My  tests are essentially empty.  I'm running on Windows using SQL Server as the database.

```
Django==1.7
django-pyodbc-azure==1.2.0
pyodbc==3.0.7
```

I did a little exploratory debugging.  The error happens when run_tests (in django/test/runner.py) calls teardown_databases().  It seems that old_config no longer has a connection associated with the sql_server.pyodbc.base.DatabaseWrapper object at the time it calls teardown_database.  

I see issues reported on django-pyodbc due to changes in 1.7 which end up with the same error which makes me suspect it's related to the latest version.  The fixes discussed there appear to be things you've already done (I think).

https://github.com/lionheart/django-pyodbc/issues/52

My workaround is to comment out the teardown_database call in my development environment:

```
    def run_tests(self, test_labels, extra_tests=None, **kwargs):
        """
        Run the unit tests for all the test labels in the provided list.

        Test labels should be dotted Python paths to test modules, test
        classes, or test methods.

        A list of 'extra' tests may also be provided; these tests
        will be added to the test suite.

        Returns the number of tests that failed.
        """
        self.setup_test_environment()
        suite = self.build_suite(test_labels, extra_tests)
        old_config = self.setup_databases()
        result = self.run_suite(suite)
        # HACK: self.teardown_databases(old_config) ## COMMENTED THIS OUT
        self.teardown_test_environment()
        return self.suite_result(suite, result)
```

**Comment by michiya** [comment]
Thank you for the reporting. Could you give me the error traceback?

**Comment by michiya** [comment]
@olivergeorge I could reproduce the error only on Linux (with FreeTDS driver), not on Windows. The fix for the error on Linux is included in the latest release of the backend, but I'm not quite sure if it also works in your case because I can't reproduce the error on Windows.

Let me know if you still receive the same error after updating the backend to the latest version.

Thanks.

**Comment by olivergeorge** [comment]
Looks good.  Thanks.

I made sure the problem was repeatable with django 1.7 and django-pyodbc-azure 1.2.0 and then retested after upgrading to 1.2.1 - problem is gone.

**Comment by michiya** [comment]
Thank you for letting me know. It's good to hear that the problem is gone now.
