### ISSUE TITLE
std::runtime_error: collate_byname<char>::collate_byname failed to construct for C/zh_CN.UTF-8

### ISSUE THREAD

**Issue by EdwardNian** [michiya/django-pyodbc-azure#164]
When I used Microsoft ODBC Driver 17 for SQL Server and django-pyodbc-azure 2.0.4.1 on Mac ,got "libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: collate_byname<char>::collate_byname failed to construct for C/zh_CN.UTF-8/C/C/C/C".

But switch to freetds, no issues happened.

When I used Microsoft ODBC Driver 17 for SQL Server and django-pyodbc-azure 1.11.0 on Mac, got 
no issues too.
Could some one help?Thanks.

**Comment by kitsuyui** [comment]
@EdwardNian 

I had the same issue too. I cannot found why it has caused yet.
But I found a workaround.
Create sitecustomize.py with following content into site-packages.

```python
import locale
locale.setlocale(locale.LC_ALL, locale.getlocale())
```

Then it works. It is worthless when setting environment variable with same.

**Comment by v-makouz** [comment]
@EdwardNian I'm looking into this, which version of ODBC Driver 17 are you using? Easy way to check is to run:
ls -l /usr/local/lib/libmsodbcsql.17.dylib

**Comment by EdwardNian** [comment]
@v-makouz /usr/local/lib/libmsodbcsql.17.dylib -> ../Cellar/msodbcsql17/17.1.0.1/lib/libmsodbcsql.17.dylib

**Comment by kitsuyui** [comment]
I think this is same problem on this:  https://github.com/Microsoft/homebrew-mssql-release/issues/18

So I think it might not be happen on the new version.

```
$ brew upgrade --no-sandbox msodbcsql17 mssql-tools
```

https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-2017

**Comment by v-makouz** [comment]
@EdwardNian Can you try the latest version (17.2.0.1)? There was a locale detection bug fixed in that one, but there may be more issues with the locales so I'm trying to gather more info.

**Comment by EdwardNian** [comment]
@kitsuyui @v-makouz 
The new version works fine!
Thank you for your kindly answer. I'll close the ticket.Thank you.
