### ISSUE TITLE
Document unicode_results

### ISSUE THREAD

**Issue by olivergeorge** [michiya/django-pyodbc-azure#18]
I was getting errors and the `unicode_results` option resolved the problem.  I don't think it's well documented.

```
DjangoUnicodeDecodeError at /Person/1425/edit/
'utf8' codec can't decode byte 0xd1 in position 5: invalid continuation byte. You passed in 'BRICE\xd1O' (<type 'str'>)
```

This is where I came across a solution:
http://stackoverflow.com/a/23013914

**Comment by michiya** [comment]
Thank you for letting me know. Now `uncode_reuslts` is also described in README as well as other available options.
