### ISSUE TITLE
Invalid object name 'information_schema.table_constraints'

### ISSUE THREAD

**Issue by kilrogg** [michiya/django-pyodbc-azure#19]
Hi.

I am using Django 1.7.4 with django-pyodbc-azure 1.2.4.

When i create my database with a collation that is case sensitive (e.g. SQL_Latin1_General_CP1_CS_AS) the schema information command fails with the error above.

Fix would be to correctly UPPERCASE the table name.

Pull request follows.

**Comment by michiya** [comment]
@kilrogg Thank you for the fix! I will push this fix to PyPI soon as a part of the next version of the backend.
