### ISSUE TITLE
State of this project

### ISSUE THREAD

**Issue by David-Engel** [michiya/django-pyodbc-azure#190]
Hi @michiya 

I'm the MS PM for SQL Server drivers. Some of our customers have noticed that this project doesn't seem to have anyone responding to issues and PRs. I understand life gets busy and people's situations change. Is there anything we can do to keep this project active? If you don't have time for it anymore and are willing to let some other people merge code, I have some resources who could help keep an eye on it for you. There are some valuable PR contributions waiting to be merged. It would be great not to lose them,

Regards,
David

**Comment by flixx** [comment]
@David-Engel can you maybe fork the repo and make it an official Microsoft driver? We also needed to disappoint some of our customers by dropping MSSQL support.
Regards
Felix

**Comment by kevin-olbrich** [comment]
> @David-Engel can you maybe fork the repo and make it an official Microsoft driver? We also needed to disappoint some of our customers by dropping MSSQL support.
> Regards
> Felix

We have similar problems with integrating SAP BO (running on MS SQL) into Django projects. Most things work for us but the quality of the module is way behind other frameworks like Zend/PHP.

I would realy like a driver, that is made by the people who develop the main product (MS SQL).

**Comment by David-Engel** [comment]
@flixx @kevin-olbrich Standing up a new driver and maintaining it going forward obviously has a cost associated with it. Having data points like these affects the funding argument when it comes time to budget for new initiatives. So thank you for your input. Comments and feedback on issues like these certainly helps us prioritize resources where our customers want them.

Thanks,
David

**Comment by wgordon17** [comment]
@David-Engel If data points help....let me take the time to give my +1 then =)

**Comment by stefanhdao** [comment]
My team is considering moving to PostgreSQL for our database since the lack of merges for this project will hinder upgrading packages in the future.

**Comment by ghost** [comment]
> My team is considering moving to PostgreSQL for our database since the lack of merges for this project will hinder upgrading packages in the future.

Unfortunately, some companies need to provide support for the infrastructure of their customers. For one of our customers the option is Oracle or SQL Server. Even though the Oracle driver is maintained inside Django, actually getting a client library installed in the docker image comes with a huge cost and it's own set of problems.

> Standing up a new driver and maintaining it going forward obviously has a cost associated with it.

So this is our datapoint. And currently we've forked and fixed issues that blocked us. It doesn't have to be a completely new driver. It's in a good enough shape to be maintained. Maybe some refactorments can benefit the long term, but what is the most benefit right now is that something maintained emerges. We're happy to drive maintenance for a bit, but without a commitment from Microsoft and maybe someone to triage and make reproducible bug reports for what's in this issue tracker, it will be on a "what affects us, we fix" basis.

**Comment by FlipperPA** [comment]
@David-Engel There was talk a few years back which included several of us who work on FreeTDS and friends to try to bring `django-pyodbc-azure` to Django core, or at least under the Django umbrella, but it would need support. There is a process for bringing projects under the Django umbrella which I could help with, if there is interest, and @Michiya is willing: https://github.com/django/

**Comment by David-Engel** [comment]
@FlipperPA I think either of those options would be great. The problem now is that michiya seems to have disappeared. He hasn't responded on any of the communication channels I have for him. What kind of support would be required?

**Comment by FlipperPA** [comment]
@David-Engel He replied in another issue saying he's working on it: https://github.com/michiya/django-pyodbc-azure/issues/192#issuecomment-481806061 The reason I'm hesitant to create a fork is there are already several `django-pyodbc` forks out there, and it is pretty confusing to newcomers. Michiya has maintained it well even with the periods of silence; every version since about 1.7 have been released within a few weeks of the Django release. I agree it would be nice to have more hands on deck, but Michiya seems to like to work on his own. :)

**Comment by bschollnick** [comment]
Well, I'm in a between a rock and a hard place.  I can't upgrade to Django v2.2 and v2.3 since I can't use Django-pyODBC-Azure, since it hasn't been updated for that Django version....

So I don't even know if they are going to support Django v3....

Having this rolled into Django, or supported by Microsoft in someway would be excellent.

**Comment by kevin-olbrich** [comment]
> Having this rolled into Django, or supported by Microsoft in someway would be excellent.

+1

**Comment by hannylicious** [comment]
I'm with @bschollnick here - we've got some systems that are needing updates to 2.2... and without this driver we're pretty sunk.

The maintainer has been silent for quite some time (I think perhaps too long) - especially given that there is a pull request out there that others say is working with 2.2 without issue.

I certainly hope that if he's feeling overwhelmed by it, he would allow someone from the community to step up and assist him.

@michiya - any ideas regarding the status of this project?

**Comment by MikeSlaught** [comment]
@David-Engel I don't know if this would be useful, but I [found a quote](https://github.com/michiya/django-pyodbc-azure/issues/41#issuecomment-134540981) from @michiya in 2015 saying:

> I'm very happy to hear that Django is going to receive support from Microsoft to provide first class support for SQL Server and Azure SQL Database! I hope Django will have its official backend implementation for SQL Server and Azure SQL Database, so you can use django-pyodbc-azure as you like to make an official one. And of course I'm willing to help you if there's anything I can.

**Comment by FlipperPA** [comment]
@David-Engel I've started a project to bring this into Django's core. I've started an issue to discuss what Microsoft's support might look like:

https://github.com/FlipperPA/django-mssql-backend/issues/8

**Comment by MikeSlaught** [comment]
Microsoft now has an official 3rd Party Backend to use SQL Server with Django! https://github.com/microsoft/mssql-django

**Comment by David-Engel** [comment]
Closed due to https://github.com/microsoft/mssql-django.
