### ISSUE TITLE
Need to add keyword parameter 'timeout' in call to Database.connect

### ISSUE THREAD

**Issue by me21** [michiya/django-pyodbc-azure#30]
The utilized pyodbc library uses keyword parameter 'timeout' in call to 'connect' to set the timeout of connection attempt. Zero value means default timeout, just like without keyword parameter. The value is set in seconds.

It is desirable to allow the user to set the timeout optionally, perhaps by adding it in 'OPTIONS'.
Example:

``` python
    DATABASES = {
        'default': {
            'ENGINE': 'sql_server.pyodbc',
            'NAME': 'guard',
            'USER': 'test',
            'PASSWORD': 'test',
            'OPTIONS': {
                'driver': 'SQL Server Native Client 10.0',
                'dsn': 'GuardLocal',
                'unicode_results': True,
                'timeout': 1,  # notice this line - one second timeout
            },
        },
    }
```

This requires one small change in Database.connect call in base.py. It should be changed from

``` python
conn = Database.connect(connstr, unicode_results=unicode_results)
```

to

``` python
conn = Database.connect(connstr, unicode_results=unicode_results, timeout=options.get('timeout', 0))
```

**Comment by michiya** [comment]
@me21 Thank you for the feedback! Now you can activate the timeout feature using the new _connection_timeout_ option in OPTIONS dict.
