### ISSUE TITLE
The combination of select_related and offset produces invalid queries on MSSQL V10.50 (2008R2)

### ISSUE THREAD

**Issue by Phist0ne** [michiya/django-pyodbc-azure#32]
When using select_related in combination with offset (slicing) django-pyodbc-azure tries to execute an invalid SQL statement which leads to an exception from the ODBC-driver.

example:

``` python
Foo.objects.select_related('bar')[100:200]
```

which will lead to the query:

``` sql
SELECT * FROM (
    SELECT [test_foo].[id], [test_foo].[bar_id], [test_foo].[some_field],
           [test_bar].[id], [test_bar].[some_other_field],
           ROW_NUMBER() OVER (
               ORDER BY [test_foo].[some_field] ASC,
               [test_bar].[some_other_field] ASC
       ) AS [rn] FROM [test_foo] INNER JOIN [test_bar] ON ( [test_foo].[bar_id] = [test_bar].[id] )
)
AS X WHERE X.rn BETWEEN 101 AND 200 ORDER BY X.rn
```

This query can not be excecuted because its resultset has 2 columns with the name "id".

**Comment by Phist0ne** [comment]
The following lines of code seem to fix the issue without interfering with other queries. Although I can not completely assure this because I am not very familiar with the Django db backend code.

``` python
# offset_emulation will cause duplicate column names in some cases
# so we fix this by overriding with_col_aliases
if do_offset and do_offset_emulation:
    with_col_aliases = True
```

(e.g. in line 39 of SQLCompiler.as_sql)

**Comment by michiya** [comment]
@Phist0ne Thank you for reporting! Your fix is correct, and the fix will be included in the next release.
