### ISSUE TITLE
Rollback transaction issue running under freetds

### ISSUE THREAD

**Issue by reggieriser** [michiya/django-pyodbc-azure#37]
I'm using freetds 0.95.18 with unixodbc 2.3.2_1 on Mac OS X 10.9.x to talk to a SQL Server 2008 R2 database.  When Django tries to save records to the database, it fails with this error (both with Django 1.7 and Django 1.8 and their corresponding django-pyodbc-azure packages):

django.db.utils.ProgrammingError: ('25000', '[25000] [FreeTDS][SQL Server]The ROLLBACK TRANSACTION request has no corresponding BEGIN TRANSACTION. (3903) (SQLEndTran)')

As far as I can tell, it appears to be coming from the rollback call in the _set_autocommit method in base.py when autocommit is being set to False but no SQL has been issued yet.  For Django 1.7, I was able to work around this issue by overriding _set_autocommit and checking the connection's is_dirty method to prevent a rollback if the transaction wasn't "dirty".  But I'm in the process of upgrading to Django 1.8 and it looks like is_dirty is no longer on the base connection class.  Not sure yet what a good fix would be.

When running under Windows and the Microsoft "ODBC Driver 11 for SQL Server" driver, I don't experience this problem.

I also tried it on a baseline startproject/startapp project and had a similar experience, including when running the "createsuperuser" management command.

Here's my DATABASES section for reference:

```
DATABASES = {
    'default': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': '-----',
        'USER': '-----',
        'PASSWORD': '-----',
        'HOST': '-----',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'FreeTDS',
            'host_is_server': True,
            'extra_params': 'TDS_VERSION=7.3',
        }
    }
}
```

**Comment by reggieriser** [comment]
I may have found a fix that works in both Django 1.7 and 1.8.  If I change the _set_autocommit method to only commit/rollback if in_atomic_block is True, things seem to work fine on both the Mac and Windows.

``` python
    def _set_autocommit(self, autocommit):
        with self.wrap_database_errors:
            if self.in_atomic_block:
                if autocommit:
                    self.connection.commit()
                else:
                    self.connection.rollback()
            self.connection.autocommit = autocommit
```

Any reason why it shouldn't be checking to see if it's in an atomic block before trying to commit or rollback?  I unfortunately don't know the database backend code well.

**Comment by FlipperPA** [comment]
Any further ideas or comments on this problem? I've run into it today for the first time with code that had been working perfectly - just doing a simple single-row update on a model to one field. I'm on v. 1.8.3 and connecting to SQL Server 2014 over FreeTDS 0.91 with TDS_VERSION set to 7.2.

```
ProgrammingError at /login/
('25000', '[25000] [FreeTDS][SQL Server]The COMMIT TRANSACTION request has no corresponding BEGIN TRANSACTION. (3902) (SQLEndTran)')
Request Method: POST
Request URL:    http://vagrant.blah.com:8000/login/
Django Version: 1.8.6
Exception Type: ProgrammingError
Exception Value:    
('25000', '[25000] [FreeTDS][SQL Server]The COMMIT TRANSACTION request has no corresponding BEGIN TRANSACTION. (3902) (SQLEndTran)')
Exception Location: /home/vagrant/.virtualenvs/wrds_classroom/lib/python3.4/site-packages/sql_server/pyodbc/base.py in _set_autocommit, line 391
Python Executable:  /home/vagrant/.virtualenvs/wrds_classroom/bin/python
Python Version: 3.4.3
```

**Comment by FlipperPA** [comment]
See Issue #46 for a possible temporary workaround:

https://github.com/michiya/django-pyodbc-azure/issues/46

**Comment by michiya** [comment]
Thank you for reporting and sorry for my delay.

I have published the new version of the backend that supports Django 1.8.6 and FreeTDS v0.95 on PyPI today, and I hope it will resolve the problem that you have now. Please let me know if you still receive the same error after updating the backend to the latest one.

**Comment by reggieriser** [comment]
I just updated to django-pyodbc-azure 1.8.7.2 (and Django 1.8.7) and removed my _set_autocommit override from above and things seem to work fine now.  Thanks!
