### ISSUE TITLE
SQLExecDirectW on add DateTimeFiled

### ISSUE THREAD

**Issue by walkingonbothsides** [michiya/django-pyodbc-azure#47]
I'm trying to add DateTimeFields to my models and get the following error:
"django.db.utils.DataError: ('22007', '[22007] [FreeTDS][SQL Server]Conversion failed when converting date and/or time from character string. (241) (SQLExecDirectW)')"

migration:

``` python
migrations.AddField(
            model_name='entrytype',
            name='creation_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 3, 12, 25, 43, 153209, tzinfo=utc), auto_now_add=True),
            preserve_default=False,
        ),
```

what the SQLServer trys to do:

``` sql
ALTER TABLE [wdok_entrytype] 
    ADD [creation_timestamp] 
        datetime DEFAULT '2015-12-03 12:25:43 +00:00' NOT NULL
```

My SQLServer-Admin says, that the query works if he removes the timezone-information. I used django.utils.timezone.now() as default-value. Should I use datetime.dateime.now() instead?

The environment:
CentOS7
FreeTDS 0.95
Django==1.8.7
django-pyodbc-azure==1.8.7.0
pyodbc==3.0.10
SQLServer 2008R2

**Comment by shaib** [comment]
This may not help with the migration, but...

**Comment by walkingonbothsides** [comment]
Thanks for the hint, I will remember it. But as you say, it doesn't matter what time it tries to use.

(in this example it really doesn't matter which time will be used for the existing fields as it is only for testing at the moment)

**Comment by michiya** [comment]
@GordonFreemem Thank you for reporting.

This is a bug of the backend. You should be able to specify not only a timezone-naive datetime object but also a timezone-aware one as a default value for DateTimeField even if it is mapped to a legacy `datetime` type column.

I have pushed the new version of the backend that contains the changes for this issue to PyPI. Please let me know if you still have the same error after updating the backend to the new one.

**Comment by walkingonbothsides** [comment]
@michiya just installed 1.8.7.2 on my test server and it run the migration.

Thank you for the quick fix :)
