### ISSUE TITLE
text fields should be excluded from GROUP BY

### ISSUE THREAD

**Issue by drakej** [michiya/django-pyodbc-azure#56]
When you attempt to aggregate fields, if the base object model has a field that's of type text (TextField in Django, "text" in SQL Server), it will cause an error when using annotation based on db compiler attempting to GROUP BY on the text field which is not allowed in SQL Server.

The result is an exception propagated from the FreeTDS stack (although it would be the native driver on windows) like the one below:

_The text, ntext, and image data types cannot be compared or sorted, except when using IS NULL or LIKE operator._

**Comment by drakej** [comment]
OK so you can exclude them which may make things very difficult given the normal Django behavior is to GROUP BY on all fields from the model object being used for the aggregates.

A way around the error is to convert the text field into a varchar.

E.G.

`Convert(Varchar(<max length>),<column name>) AS <column name>`

The drawback is truncation of the field which may cause odd side effects if the field in question has multiple values that truncate to the same value when limited to the max varchar length. That would cause the aggregates to break anyways.

**Comment by shaib** [comment]
This problem is not unique to SQL Server and IMO it is not the backend's job to solve it; see https://code.djangoproject.com/ticket/24096

**Comment by drakej** [comment]
Fair enough. I wasn't sure if Django expects to solve it or not. I also realized an easy way around it without requiring any changes to the models or schema is to just use the values() method. You don't get back a QuerySet with model instances, but then again if you're running into this issue, you probably don't even need all of the fields to be grouped anyways.
