### ISSUE TITLE
Support for count_big?

### ISSUE THREAD

**Issue by whelks-chance** [michiya/django-pyodbc-azure#60]
('22003', '[22003] [Microsoft][ODBC SQL Server Driver][SQL Server]Arithmetic overflow error converting expression to data type int. (8115) (SQLExecDirectW)')

That's the error I'm getting while trying to use Django Admin on a table with 2.8 billion rows. As far as I can tell, a count() query is run when loading the page, in order to work out pagination, which I think is using count() instead of count_big, so the overflow occurs.

https://msdn.microsoft.com/en-us/library/ms190317.aspx

I hope that makes sense?

**Comment by michiya** [comment]
@whelks-chance Thank you for reporting! I've made the fix for the issue as a part of f7306af and it will be pushed to PyPI soon.

**Comment by whelks-chance** [comment]
Great! Thank very much.

**Comment by michiya** [comment]
Closing the issue because the new version of the package that contains the fix is now available on PyPI. Feel free to open a new issue if you still have a problem.
