### ISSUE TITLE
Accessing tables in a schema doesn't seem to work in legacy DB

### ISSUE THREAD

**Issue by kdazzle** [michiya/django-pyodbc-azure#67]
I'm not too familiar with MSSQL, so let me know if any terminology is wrong, but is there a supported way to access tables within a schema? For example, say I have a legacy database and there is a schema called `Products`, and that schema contains a table `Coats`.

So I set up my Django model:

```
class Coat(models.Model):

    # attributes...

    class Meta:
        is_managed = False
        db_table = 'Coats'  # This is the tricky part
```

There doesn't seem like there is any good way to set the `db_table`. I've tried `Coats`, `Products.Coats`, `COATS`, `Products/Coats`, etc. etc.

However, there is a gross way to make it work that I found [here](http://kozelj.org/django-1-6-mssql-and-schemas/), which uses some injection. So using that, we'd set `db_table = 'Products].[Coats'`. 

Surely someone has faced this before - is there a better way to access tables in a schema? If not, maybe I can submit a PR to institutionalize this method because it was tough to even find a workaround for.

Thanks!

**Comment by michiya** [comment]
Unfortunately django-pyodbc-azure currently doesn't provide support for database schemas as well as the other standard database backends. See the following ticket for more details about database schema support in Django.
https://code.djangoproject.com/ticket/6148

As a workaround, you can use a database schema by specifying it as the default schema for your database user. Note that you can't assign `sysadmin` or `db_owner` role to a user that you want to specify its default schema as described in the following page.
https://social.msdn.microsoft.com/Forums/sqlserver/en-US/a1155e64-e53f-4e20-9b1d-4f31e193b14e/default-schema-not-working

T-SQL to create a new user for this would look like the following. Of course you also can do this using SQL Server Management Studio.

```
USE MASTER
CREATE LOGIN myuser WITH PASSWORD='password'
GO

USE mydb
CREATE USER myuser FOR LOGIN myuser WITH DEFAULT_SCHEMA = Products
ALTER ROLE db_ddladmin ADD MEMBER myuser
ALTER ROLE db_datareader ADD MEMBER myuser
ALTER ROLE db_datawriter ADD MEMBER myuser
GO
```

And then you can specify the user created above for `USER` in your `DATABASES` settings.

Hope this helps.

**Comment by kdazzle** [comment]
Thanks for the response and the other workaround @michiya! Looks like that django issue might even be resolved soon.

**Comment by ghost** [comment]
@michiya Is there a way to have multiple schemas, each with `django_migrations`? Please check my issue here for details: https://github.com/michiya/django-pyodbc-azure/issues/133. Essentially, creating a second project and attempting to interact with the database seems to cause the introspection to look for `django_migrations` at the database level, not the schema level.
