### ISSUE TITLE
Wheel support

### ISSUE THREAD

**Issue by kevin-brown** [michiya/django-pyodbc-azure#76]
http://pythonwheels.com/

Right now, only the `zip` file is being distributed on PyPI for [django-pyodbc-azure](https://pypi.python.org/pypi/django-pyodbc-azure), which isn't _that much_ of an issue, but it does add some time to installing the package.

This package should be compatible with the Wheel format, considering it doesn't appear to have any C dependencies and it is compatible with both Python 2 and 3. As a result, you should only need to generate a universal wheel and then everyone (on all systems) will get the ability to install django-pyodbc-azure with just the wheel, without having to do any extra work.

**Comment by michiya** [comment]
@kevin-brown Thank you for the feedback. I've pushed the new version of django-pyodbc-azure as a wheel and I will continue publishing the package on PyPI with the wheel format in the future.

**Comment by michiya** [comment]
Closing the issue because the wheel package is now available on PyPI.
