### ISSUE TITLE
Query for version on every request

### ISSUE THREAD

**Issue by aergener** [michiya/django-pyodbc-azure#80]
I am trying to switch to `django-pyodbc-azure`, but I noticed that on every request this SQL command is executed, which is causing a lot of additional latency:

`QUERY = "SELECT CAST(SERVERPROPERTY('ProductVersion') AS varchar)"`

Looks like it is due to this portion of the code: https://github.com/michiya/django-pyodbc-azure/blob/azure-1.10/sql_server/pyodbc/base.py#L390

Is this the expected behavior? If so, is there a way to change this, or set the value ahead of time?

**Comment by FlipperPA** [comment]
Could this be a case of `@cached_property` not working as intended due to the life of the instance?

**Comment by aergener** [comment]
I'm not entirely sure how `@cached_property` works. Is the cached value supposed to last for the duration of the request, or for the entire life of the django process?

**Comment by aergener** [comment]
After doing some digging, [`@cached_property`](https://github.com/django/django/blob/master/django/utils/functional.py#L19) caches the property on the instance. The `DatabaseWrapper` class is used to establish a connection to the database, and a new connection is established on each request. Since the value is cached on the _instance_ and not the _class_, this means that the property will be evaluated each time `DatabaseWrapper` is instantiated, which is every time a request is made.

I believe this could be solving by caching the property on the class instead of the instance. @michiya will you merge that change if I open a PR?

**Comment by aergener** [comment]
Until I hear back from @michiya, this behavior can prevented by monkey-patching `sql_server_version` in `settings.py`:

```python
from sql_server.pyodbc.base import DatabaseWrapper
DatabaseWrapper.sql_server_version = '2012'
```

Swap out '2012' for your sql_server_version.

**Comment by diegojancic** [comment]
Thanks @aergener. The solution for me was the following however (quotes removed around the version number:

```
from sql_server.pyodbc.base import DatabaseWrapper
DatabaseWrapper.sql_server_version = 2012
```

For anyone reading, valid version numbers are as follows. Execute `SELECT CAST(SERVERPROPERTY('ProductVersion') AS varchar)` and use the major version number (eg, `12` if the full version is `12.0.4487.0`). Then use the year/version number based on the following list:

```
9: 2005
10: 2008
11: 2012
12: 2014
13: 2016
```

**Comment by FlipperPA** [comment]
I just realized there hasn't been a PR issued for this. I'm happy to take the lead on it, if no one else responds? Fairly simple, with huge benefits.

**Comment by diegojancic** [comment]
Please. Thank you!
