### ISSUE TITLE
Support WITH (NOLOCK)

### ISSUE THREAD

**Issue by chris-nlnz** [michiya/django-pyodbc-azure#82]
I've been asked to implement our application so any `SELECT` queries will be done with the `WITH (NOLOCK)` setting (i.e. `SELECT * FROM [TableName] WITH (NOLOCK);`).  

I couldn't find any support for this in django-pyodbc-azure, and couldn't find this functionality being discussed anywhere.  

For our own purposes I'll create a fork of this repo where we can use `WITH (NOLOCK)`. Would you be interested in a pull request with this functionality?

**Comment by michiya** [comment]
Now you can perform dirty reads by setting isolation_level option in your database settings to `READ UNCOMMITTED`. See README for more details.

**Comment by MarkBird** [comment]
I'd like to see the requested feature added if possible, setting isolation level in database settings makes EVERY query a dirty read, which isn't necessarily desirable.

If possible, can we have the option to make a *query* use NOLOCK without having to set it globally?
