### ISSUE TITLE
Select Related with slicing fails with a multiple 'id' specified error

### ISSUE THREAD

**Issue by yoavimoo** [michiya/django-pyodbc-azure#9]
Tested on tag 1.0.9
but should be relevant for the current master branch as well.

Using the following models as an example:
models.py:
from django.db import models

class Hat(models.Model):
name = models.CharField(max_length=64)

class Head(models.Model):
name = models.CharField(max_length=64)
hat = models.ForeignKey(Hat)

def **unicode**(self):
    return "%s wearing a hat %s" % (self.name, self.hat.name)
executing the following query:
Head.objects.select_related("hat").all()[100:200]

Resulting error:
DatabaseError: ('42000', "[42000] [Microsoft][SQL Server Native Client 10.0][SQLServer]The column 'id' was specified multiple times for 'X'. (8156) (SQLExecDirectW)")

Optional fix available in:
https://github.com/yoavimoo/django-pyodbc-azure/commit/dc09a3ef7063b704e7ba46b79f973e503be2b5b9

**Comment by michiya** [comment]
@yoavimoo Thank you for the fix! I have integrated your fix into the repository, and the new version of the package that contains the fix will be pushed to PyPI soon.

**Comment by michiya** [comment]
The new versions (1.0.11 and 1.1.4) are now available on PyPI.
