### ISSUE TITLE
Support for django 1.11

### ISSUE THREAD

**Issue by LegoStormtroopr** [michiya/django-pyodbc-azure#91]
[Django 1.11 is now out](https://www.djangoproject.com/weblog/2017/apr/04/django-111-released/), is there a timeframe for support?

**Comment by michiya** [comment]
Hi,
Sorry for my delay. Now I'm updating the backend codes and testing them on Django 1.11. I hope I will publish the new version that supports Django 1.11 in a week or so.

**Comment by FlipperPA** [comment]
Thanks @michiya! Is there anything we can do to help out? Looking forward to subselects!

**Comment by matteing** [comment]
Also pumped for this.

**Comment by daybarr** [comment]
For those watching this ticket that might be unaware, 1.11 support was released yesterday. Thanks again @michiya , great job 👍

https://github.com/michiya/django-pyodbc-azure/releases/tag/1.11.0.0
