### ISSUE TITLE
Whys does DateField result in datetime column?

### ISSUE THREAD

**Issue by unformatt** [michiya/django-pyodbc-azure#93]
My model has a DateField, like so:

`timestamp = models.DateField()`

I create and run migrations, I end up with a `datetime` column rather than `date`. This has never been a problem since, somehow, Django is always given a python `date` for that field even though the column is datetime. e.g.

```
>>> SP.objects.all()[0].timestamp
datetime.date(2017, 5, 2)
```

I'm using unixodbc/freetds on Ubuntu 16. My driver is set to `/usr/lib/x86_64-linux-gnu/odbc/libtdsodbc.so`

What's interesting is I was testing with Microsoft's Linux ODBC driver (set Driver to `/opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.1.so.6.0`). If I do that and recreate my DB, then the migration creates a `date` column. (Note that the migration code is exactly the same)

To make this even more confusing, if I run the migration on Windows (so that neither unixodbc/freetds or MS's Linux odbc driver is involved) using MS's Windows ODBC Driver, I get a `datetime` column. So somehow, it's ok to have a `datetime` column for a DateField, it hasn't caused me problems until now.

Why does this all matter?

The problem is that I have database that was created via unixodbc/freetds. When I try to connect to that database from Linux using MS's Linux ODBC driver, the models returns a python datetime rather than date and this causes Exceptions in code that's already written and expects a python date. For example:

With unixodbc/freetds:
```
>>> SP.objects.all()[0].timestamp
datetime.date(2017, 5, 2)
```

Same exact database but accessed with MS's Linux driver:

```
>>> SP.objects.all()[0].timestamp
datetime.datetime(2017, 5, 2, 0, 0)
```

Any idea what is going on far beneath the surface?

**Comment by meet-bhagdev** [comment]
@unformatt Let me know if this is a MS Linux ODBC Driver issue. I can work with Michiya and our team at Microsoft to fix this bug in the driver 👍

**Comment by john20xdoe** [comment]
Experiencing this too. Maybe a bit related. 

We are currently upgrading Serene to 2.9 from 2.4. Our database is SQL Server.

A `DateTime` column in our row has a QuickFilter attribute, previously showing as a DateEditor. Upon upgrade, it is now showing a `DateTimeEditor`. 

Trying to force it as `[DateEditor]` both in Columns or Row does nothing, still a `DateTimeEditor` quickfilter.

However, in the demo: http://serenity.is/demo/BasicSamples/InitialValuesForQuickFilters the OrderDate QuickFilter is a DateTime but still uses DateEditor.

**Comment by unformatt** [comment]
Hello again @meet-bhagdev :)

I don't know enough about how django-pyodbc-azure works to know where the problem lies. I did some more debugging and I compared the SQL generated by django+django-pyodbc-azure when creating the table during the migration:

**Using MS Linux ODBC Driver**
```sql
CREATE TABLE [main_stockprice] (
[id] int IDENTITY (1, 1) NOT NULL PRIMARY KEY, 
[symbol] nvarchar(50) NOT NULL, 
[price] numeric(15, 4) NOT NULL, 
[timestamp] date NOT NULL);  --  date is used
```


**Using unixodbc**
```sql
CREATE TABLE [main_stockprice] (
[id] int IDENTITY (1, 1) NOT NULL PRIMARY KEY, 
[symbol] nvarchar(50) NOT NULL,
[price] numeric(15, 4) NOT NULL,
[timestamp] datetime NOT NULL);  --  datetime is used
```

I will try to dig deeper unless @michiya pops up

**Comment by unformatt** [comment]
So **django-pyodbc-azure** says that my driver (/usr/local/lib/libtdsodbc.so) doesn't support `date` column type. For my setup, it's making this decision here: https://github.com/michiya/django-pyodbc-azure/blob/azure-1.11/sql_server/pyodbc/base.py#L373

```python
            val = cursor.execute('SELECT SYSDATETIME()').fetchone()[0]
            if isinstance(val, text_type):
                # the driver doesn't support the modern datetime types
                self.use_legacy_datetime = True
```

So freetds does not support `date` column type?

**Comment by unformatt** [comment]
A related conversation about freetds and dates: https://github.com/pymssql/pymssql/issues/156#issuecomment-31922629

**Comment by unformatt** [comment]
Figured out the solution. Since my database was created using freetds, `use_legacy_datetime` was automatically set to True. When I change to MS's ODBC driver, `use_legacy_datetime` reverts back to its default of False. But since I'm accessing a database that was created while `use_legacy_datetime` was True, I need to force `use_legacy_datetime` True in django's DATABASES settings to force the proper processing of the `datetime` columns.
